In [8]:
import cv2
import numpy as np
import math

In [9]:
img = cv2.imread('1.jpg',0)

In [10]:
def rotate_about_center(src, angle, scale=1.):
    w = src.shape[1]
    h = src.shape[0]
    rangle = np.deg2rad(angle)  # angle in radians
    # now calculate new image width and height
    nw = (abs(np.sin(rangle)*h) + abs(np.cos(rangle)*w))*scale
    nh = (abs(np.cos(rangle)*h) + abs(np.sin(rangle)*w))*scale
    # ask OpenCV for the rotation matrix
    rot_mat = cv2.getRotationMatrix2D((nw*0.5, nh*0.5), angle, scale)
    # calculate the move from the old center to the new center combined
    # with the rotation
    rot_move = np.dot(rot_mat, np.array([(nw-w)*0.5, (nh-h)*0.5,0]))
    # the move only affects the translation, so update the translation
    # part of the transform
    rot_mat[0,2] += rot_move[0]
    rot_mat[1,2] += rot_move[1]
    return cv2.warpAffine(src, rot_mat, (int(math.ceil(nw)), int(math.ceil(nh))), flags=cv2.INTER_LANCZOS4)

In [11]:
for rotation_angle in range(-180, 180):
    
    dst = rotate_about_center(img,rotation_angle,1)
    cv2.imshow('img',dst)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cv2.destroyAllWindows()

In [12]:
there = rotate_about_center(img,90,1)
w_or = there.shape[1]
h_or = there.shape[0]

angle = 90
scale = 1
rangle = np.deg2rad(angle)  # angle in radians
# now calculate new image width and height
nw_there = (abs(np.sin(rangle)*h_or) + abs(np.cos(rangle)*w_or))*scale
nh_there = (abs(np.cos(rangle)*h_or) + abs(np.sin(rangle)*w_or))*scale

In [13]:
back = rotate_about_center(there,-90,1)
w = back.shape[1]
h = back.shape[0]

rangle = np.deg2rad(angle)  # angle in radians
# now calculate new image width and height
nw_back = (abs(np.sin(rangle)*h) + abs(np.cos(rangle)*w))*scale
nh_back = (abs(np.cos(rangle)*h) + abs(np.sin(rangle)*w))*scale

In [14]:
cv2.imwrite("result.jpg", back)

True

### Coordinates in original picture

In [15]:
import numpy as np
import math
import cv2

In [16]:
src = cv2.imread('1.jpg',0)
h, w = src.shape

In [17]:
x = 0
y = 0
my_point = np.array([[x], [y]])

In [18]:
# Meret novekedes ay eredeti forgatasbol
angle = 90
scale = 1
rangle = np.deg2rad(angle)  # angle in radians
# now calculate new image width and height
nw_there = (abs(np.sin(rangle)*h_or) + abs(np.cos(rangle)*w_or))*scale
nh_there = (abs(np.cos(rangle)*h_or) + abs(np.sin(rangle)*w_or))*scale
nw_there, nh_there

(640.0, 481.00000000000006)

In [36]:
# Centrum eltolasa a sarokbol a centruma
eltolasi_vektor_centrumba = np.array([[w/2], [-h/2]]) 

my_point_ctc = my_point + eltolasi_vektor_centrumba
my_point_ctc

array([[ 320],
       [-240]], dtype=int64)

In [37]:
# Visszaforgatas
angle = -90
theta = np.deg2rad(angle)
rotMatrix = np.array([[np.cos(theta), -np.sin(theta)], 
                      [np.sin(theta),  np.cos(theta)]])
elforgatott_pont = np.dot(rotMatrix, my_point_ctc)
elforgatott_pont

array([[-240.],
       [-320.]])

In [38]:
# Eltolasi vertor elforgatasa

elforgatott_eltolasi_vektor = np.dot(rotMatrix, eltolasi_vektor_centrumba)
elforgatott_eltolasi_vektor

array([[-240.],
       [-320.]])

In [41]:
#Centrum visszatolasa a centrumbol a sarokba
elforgatott_pont - eltolasi_vektor_centrumba

array([[-560.],
       [ -80.]])

In [36]:
# Kompenyalas a elforgatasbol eredo meretnovekedessel
x_final = x_acc - (nw_there-w)/2
y_final = y_acc - (nh_there-h)/2

In [37]:
x_final, y_final

(array([ 560.]), array([ 79.5]))

In [77]:
theta = math.pi
rotMatrix = np.array([[np.cos(theta), -np.sin(theta)], 
                      [np.sin(theta),  np.cos(theta)]])

In [79]:
np.dot(rotMatrix, my_point)

array([[ -8.00000000e+01],
       [  9.79717439e-15]])

array([  3.43387484e-07])

array([-79.99258771])