In [101]:
import cv2
import numpy as np
import math

In [272]:
img = cv2.imread('1.jpg',0)

In [273]:
def rotate_about_center(src, angle, scale=1.):
    w = src.shape[1]
    h = src.shape[0]
    rangle = np.deg2rad(angle)  # angle in radians
    # now calculate new image width and height
    nw = (abs(np.sin(rangle)*h) + abs(np.cos(rangle)*w))*scale
    nh = (abs(np.cos(rangle)*h) + abs(np.sin(rangle)*w))*scale
    # ask OpenCV for the rotation matrix
    rot_mat = cv2.getRotationMatrix2D((nw*0.5, nh*0.5), angle, scale)
    # calculate the move from the old center to the new center combined
    # with the rotation
    rot_move = np.dot(rot_mat, np.array([(nw-w)*0.5, (nh-h)*0.5,0]))
    # the move only affects the translation, so update the translation
    # part of the transform
    rot_mat[0,2] += rot_move[0]
    rot_mat[1,2] += rot_move[1]
    return cv2.warpAffine(src, rot_mat, (int(math.ceil(nw)), int(math.ceil(nh))), flags=cv2.INTER_LANCZOS4)

In [274]:
for rotation_angle in range(-180, 180):
    
    dst = rotate_about_center(img,rotation_angle,1)
    cv2.imshow('img',dst)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cv2.destroyAllWindows()

In [10]:
there = rotate_about_center(img,45,1)
w_or = there.shape[1]
h_or = there.shape[0]

angle = 90
scale = 1
rangle = np.deg2rad(angle)  # angle in radians
# now calculate new image width and height
nw_there = (abs(np.sin(rangle)*h_or) + abs(np.cos(rangle)*w_or))*scale
nh_there = (abs(np.cos(rangle)*h_or) + abs(np.sin(rangle)*w_or))*scale

In [6]:
back = rotate_about_center(there,-90,1)
w = back.shape[1]
h = back.shape[0]

rangle = np.deg2rad(angle)  # angle in radians
# now calculate new image width and height
nw_back = (abs(np.sin(rangle)*h) + abs(np.cos(rangle)*w))*scale
nh_back = (abs(np.cos(rangle)*h) + abs(np.sin(rangle)*w))*scale

In [11]:
cv2.imwrite("result.jpg", there)

True

### Coordinates in original picture

In [ ]:
import numpy as np
import math
import cv2

In [282]:
def calulate_original_coordinat_before_rotation(original_image, rotated_image, point, angle):
    w_original = original_image.shape[1]
    h_original = original_image.shape[0]

    w_rotated = rotated_image.shape[1]
    h_rotated = rotated_image.shape[0]
    
    # From top left coorner to centrum of image
    centrum_vector = np.array([[-w_rotated/2], [-h_rotated/2]])

    point_relative_to_centrum = point + centrum_vector

    # Rotation back
    theta = np.deg2rad(angle)
    rotMatrix = np.array([[np.cos(theta), -np.sin(theta)], 
                          [np.sin(theta),  np.cos(theta)]])
    rotated_point_relative_to_centrum = np.dot(rotMatrix, point_relative_to_centrum)

    # Centrum to top left coorner
    top_left_centrum_point = rotated_point_relative_to_centrum - centrum_vector
    
    # Compenyation with picture growth
    w_growth_on_one_side = (w_rotated-w_original) / 2 
    h_growth_on_one_side = (h_rotated-h_original) / 2
    compensation_vector = np.array([[w_growth_on_one_side],[h_growth_on_one_side]])
    
    original_point = top_left_centrum_point - compensation_vector
    
    return (original_point)

In [287]:
calulate_original_coordinat_before_rotation(img, there, np.array([[450],[0]]), 45)



array([[ 638.19805153],
       [  -1.83051917]])

In [269]:
my_point = np.array([[0],[450]])

In [279]:
there = rotate_about_center(img,45,1)
w_or = there.shape[1]
h_or = there.shape[0]
w_or, h_or

(792L, 792L)

In [280]:
# centrum a kozéppont
centrum1 = np.array([[-w_or/2], [-h_or/2]])
centrum1

array([[-396],
       [-396]], dtype=int64)

In [281]:
step1 = my_point + centrum1
step1

array([[-396],
       [  54]], dtype=int64)

In [263]:
# Rotation back
theta = np.deg2rad(45)
rotMatrix = np.array([[np.cos(theta), -np.sin(theta)], 
                      [np.sin(theta),  np.cos(theta)]])
step2 = np.dot(rotMatrix, step1)
step2

array([[-318.19805153],
       [-241.83051917]])

In [264]:
step2 - centrum1 

array([[  77.80194847],
       [ 154.16948083]])

array([[-558.22662223],
       [  78.19805153]])

In [266]:
# Eredeti képpel visszatolni
original_rotation = np.deg2rad(45) 
nw_there = (abs(np.sin(original_rotation)*480) + abs(np.cos(original_rotation)*640))*scale
nh_there = (abs(np.cos(original_rotation)*480) + abs(np.sin(original_rotation)*640))*scale
(nw_there-640)/2, (nh_there-480)/2

(75.979797464466628, 155.97979746446663)